version: 2

project_name: opsmate

builds:
  - id: opsmate
    main: ./cmd/opsmate
    binary: opsmate
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w -X github.com/HediAbed/opsmate/internal/version.release={{ .Version }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - ids:
      - opsmate
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - VERSION

sboms:
  - id: archives
    artifacts: archive
    disable: false

checksum:
  name_template: checksums.txt
  algorithm: sha256

signs:
  - id: checksum
    cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - sign-blob
      - "--bundle=${signature}"
      - "${artifact}"
      - --yes
    artifacts: checksum

changelog:
  use: git
  sort: asc

release:
  draft: true
